### ISSUE TITLE
Footer Bar text color not saving....

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/storefront-footer-bar#1]
WordPress 4.9.1
Storefront 2.2.5
Homestore 2.0.21
Footer Bar 1.0.3

When using Storefront Footer Bar, the following bug appears:

Customizer > Footer Bar > Text color

Choose any color. It reflects correctly in the Customizer.

But after publishing and closing Customizer, you will notice is has reverted back to the whitish default color.

**Comment by mikejolley** [comment]
Could this saving issue be related to https://github.com/woocommerce/storefront-mega-menus/issues/90?

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/homestore/issues/31
