### ISSUE TITLE
Pages reloading when footer bar background image not defined

### ISSUE THREAD

**Issue by bobbingwide** [woocommerce/storefront-footer-bar#2]
Migrating a site from Canvas to Storefront I downloaded the Storefront Extensions Bundle and started using the footer bar. 
After a while I noticed that every page request was being repeated. I eventually tracked it down to this plugin, determining that the problem occurred when no background image was defined for the footer bar.

### Fix
The logic should be changed to not create the `background-image` property for `.sfb-footer-bar` when $footer_bar_bg_image is not set. 

### Workaround
Set a background image.

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/storefront-footer-bar/commit/313b73463d6f9949eff33a8c1d4e5cbf76462f88
