### ISSUE TITLE
displaying the footer bar conditionally (on sopme pages only)

### ISSUE THREAD

**Issue by hsaada** [woocommerce/storefront-footer-bar#5]
Hi there,

First, thank you for providing this plugin. This is not really an issue but more of a feature request: How would I go about hiding the footer bar on the cart and checkout pages? 

Thanks and keep up the good work! :)

**Comment by hsaada** [comment]
Hi again,

I ended up modifying and adding the following code in bold at the end of storefront-footer-bar.php at to solve my issue:

	/**
	 * Footer bar display
	 */
	public function sfb_footer_bar() {
		if ( is_active_sidebar( 'footer-bar-1' ) **&& !is_checkout() && !is_cart()** ) {

			echo '<div class="sfb-footer-bar"><div class="col-full">';
				dynamic_sidebar( 'footer-bar-1' );
			echo '</div></div>';
		}
	}
} // End Class

I'm sure there's a better way to handle this but wanted to put this solution in case someone was looking for a similar hack. Thanks guys!

**Comment by GlennMartin1** [comment]
You could hide with CSS.

```
.page-id-123 div.sfb-footer-bar {
	display: none;
}
```

where "123" is the page ID #.
